version: '2.4'

services:
  postgres:
    image: postgres:14.1
    cpus: 4
    mem_limit: 4096m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -q -h postgres -U petclinic"
      interval: 3s
      timeout: 5s
      retries: 15

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://petclinic:petclinic@postgres:5432/petclinic?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  petclinic:
    image: kotoant/spring-petclinic-rest-webmvc-jdbc
    cpus: 4
    mem_limit: 4096m
    ports:
      - "9966:9966"
    command: >
      --spring.profiles.active=postgresql,spring-data-jpa,project-loom
      --spring.datasource.url=jdbc:postgresql://postgres/petclinic
      --spring.datasource.hikari.connection-test-query='select 1'
      --spring.datasource.hikari.connection-timeout=30000
      --spring.datasource.hikari.idle-timeout=300000
      --spring.datasource.hikari.max-lifetime=1800000
      --spring.datasource.hikari.maximum-pool-size=95
      --spring.datasource.hikari.minimum-idle=10
      --spring.datasource.hikari.validation-timeout=5000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
